#!/bin/bash

echo "🔑 Getting Firebase Configuration"
echo "=================================="
echo ""
echo "Your project ID: pho-finder-5175f"
echo ""
echo "To get your Firebase config:"
echo ""
echo "1. Open: https://console.firebase.google.com/project/pho-finder-5175f/settings/general"
echo ""
echo "2. Scroll down to 'Your apps' section"
echo ""
echo "3. If you don't see a web app, click the '</>' icon to add one"
echo "   - App nickname: PhoFinder"
echo "   - Don't check 'Also set up Firebase Hosting'"
echo "   - Click 'Register app'"
echo ""
echo "4. Copy the config values from the code snippet"
echo ""
echo "5. The values you need are:"
echo "   - apiKey (NEXT_PUBLIC_FIREBASE_API_KEY)"
echo "   - authDomain (NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN)"
echo "   - projectId (NEXT_PUBLIC_FIREBASE_PROJECT_ID)"
echo "   - storageBucket (NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET)"
echo "   - messagingSenderId (NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID)"
echo "   - appId (NEXT_PUBLIC_FIREBASE_APP_ID)"
echo ""
echo "6. Update .env.local with these values"
echo ""
echo "Opening Firebase Console..."
open "https://console.firebase.google.com/project/pho-finder-5175f/settings/general" 2>/dev/null || echo "Please open the URL above manually"
